from google import genai
import os
import logging
from typing import List, Dict
from datetime import datetime

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Configure Gemini API
API_KEY = os.getenv("GOOGLE_API_KEY")

class EmailAgent:
    def __init__(self, model_name: str = "gemini-2.5-flash"):
        if not API_KEY:
            logger.warning("GOOGLE_API_KEY not found. Agent will fail.")
            self.client = None
        else:
            self.client = genai.Client(api_key=API_KEY)
        self.model_name = model_name

    def generate_intro(self, user_name: str, top_news_titles: List[str]) -> str:
        """
        Generates a personalized email introduction based on the day's top news themes.
        """
        if not self.client:
            return f"Hello {user_name}, here is your daily digest."

        titles_text = "\n".join([f"- {t}" for t in top_news_titles])
        today = datetime.now().strftime("%A, %B %d")

        prompt = (
            f"You are writing a friendly, professional email newsletter introduction for {user_name}. "
            f"Date: {today}.\n"
            f"Here are the top news headlines for today:\n{titles_text}\n\n"
            f"Task: Write a short (2-3 sentences) opening paragraph. "
            f"Mention the key themes appearing in these headlines (e.g. 'Today is big on AI Agents...'). "
            f"Keep it engaging and concise. Do not use 'Subject:' line, just the body text start."
        )

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt
            )
            if response.text:
                return response.text.strip()
            return f"Hello {user_name}, here are your top stories for today."
        except Exception as e:
            logger.error(f"Error generating email intro: {e}")
            return f"Hello {user_name}, here are your top stories for today."

    def format_email(self, user_name: str, intro: str, ranked_data: List[Dict]) -> str:
        """
        Formats the final email in HTML.
        ranked_data should be a list of dicts with: title, url, date, reasoning, summary.
        """
        
        # Limit to Top 10 just in case
        items = ranked_data[:10]
        
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto;">
                <h2>Daily AI Digest</h2>
                <p>{intro}</p>
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                
                <ul style="list-style-type: none; padding: 0;">
        """
        
        for item in items:
            title = item.get('title', 'No Title')
            url = item.get('url', '#')
            date = item.get('date', '')
            reason = item.get('reasoning', '')
            summary = item.get('summary', '')[:200] + "..." # Snippet
            
            html_content += f"""
                <li style="margin-bottom: 25px; padding-bottom: 15px; border-bottom: 1px solid #f0f0f0;">
                    <h3 style="margin: 0 0 5px 0;">
                        <a href="{url}" style="color: #0066cc; text-decoration: none;">{title}</a>
                    </h3>
                    <div style="font-size: 0.85em; color: #777; margin-bottom: 8px;">
                        {date}
                    </div>
                    <div style="background-color: #f9f9f9; padding: 10px; border-radius: 5px; font-size: 0.9em; margin-bottom: 8px;">
                        <strong>Why it matters:</strong> {reason}
                    </div>
                    <div style="font-size: 0.95em;">
                        {summary}
                    </div>
                </li>
            """
            
        html_content += """
                </ul>
                <p style="font-size: 0.8em; color: #888; text-align: center; margin-top: 30px;">
                    Generated by your AI News Aggregator
                </p>
            </div>
        </body>
        </html>
        """
        
        return html_content

if __name__ == "__main__":
    # Test
    agent = EmailAgent()
    print("Testing Email Agent...")
    intro = agent.generate_intro("Shashank", ["OpenAI releases GPT-5", "Anthropic updates Claude"])
    print(f"Intro: {intro}")
